#!/bin/sh

#Hard coded to take from a specific engine. 
#Make this image take engine name as a parameter
cp -r /tmp/src/engine/${ENGINE}/* /usr/local/tomcat/webapps/

#Future: you can also look for presence of Maven pom file and sources and can build here
#At that time, AppPackage can have source files and Pom file instead of WAR files for better developer productivity
